name: Java Maven Build and Verify

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AdoptOpenJDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Use '17' or other appropriate versions
        distribution: 'adopt' # Specify the distribution (AdoptOpenJDK)

    - name: Build with Maven (compile)
      run: mvn compile

    - name: Package with Maven
      run: mvn package

    - name: Verify with Maven
      run: mvn verify
